language: java
jdk:
- oraclejdk8
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_dcd7aa55d643_key -iv $encrypted_dcd7aa55d643_iv
  -in etc/secrets -out ../secrets.tar -d
- (cd ../ && tar xvf secrets.tar)
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package publish_if_tagged
git:
  depth: 10
