repositories:
  remote:
   - https://github.com/realityforge/repository/raw/master
   - http://repo1.maven.org/maven2
   - http://download.eclipse.org/rt/eclipselink/maven.repo

artifacts:
  javax_inject: javax.inject:javax.inject:jar:1
  javax_ejb: org.apache.geronimo.specs:geronimo-ejb_3.1_spec:jar:1.0.2
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  javax_transaction: javax.transaction:jta:jar:1.1
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  javax_interceptor: org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.1_spec:jar:1.0.0.Final
  javax_jaxrpc: javax.xml:jaxrpc-api:jar:1.1
  javax_jms: org.apache.geronimo.specs:geronimo-jms_1.1_spec:jar:1.1.1
  javax_mail: javax.mail:mail:jar:1.4.1

  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice
  testng: org.testng:testng:jar:6.8
  mockito: org.mockito:mockito-all:jar:1.9.5
  eclipselink: org.eclipse.persistence:eclipselink:jar:2.3.0
  jndikit: org.realityforge.jndikit:jndikit:jar:1.4
  # Lightweight mail server for testing
  greenmail: com.icegreen:greenmail:jar:1.3.1

  h2db: com.h2database:h2:jar:1.3.159

  glassfish_embedded: org.glassfish.main.extras:glassfish-embedded-all:jar:3.1.2.2
  jtds: net.sourceforge.jtds:jtds:jar:1.3.1
